'use strict';
angular.module('app').config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	$stateProvider.state('main',{
		url:'/main',
		templateUrl:'view/main.html',
		controller:'mainCtrl'
	}).state('search',{ 
		url:'/search/:id',
		templateUrl:'view/search.html',
		controller:'searchCtrl'
	}).state('me',{ 
		url:'/me',
		templateUrl:'view/me.html',
		controller:'meCtrl'
	}).state('grLogin',{ 
		url:'/grLogin',
		templateUrl:'view/template/grLogin.html',
		controller:'grLoginCtrl'
	}).state('qyLogin',{ 
		url:'/qyLogin',
		templateUrl:'view/template/qyLogin.html',
		controller:'qyLoginCtrl'
	}).state('grRegister',{ 
		url:'/grRegister',
		templateUrl:'view/template/grRegister.html',
		controller:'grRegisterCtrl'
	}).state('qyRegister',{ 
		url:'/qyRegister',
		templateUrl:'view/template/qyRegister.html',
		controller:'qyRegisterCtrl'
	}).state('position',{ 
		url:'/position/:id',
		templateUrl:'view/template/position.html',
		controller:'positionCtrl'
	}).state('favorite',{ 
		url:'/position',
		templateUrl:'view/template/favorite.html',
		controller:'favoriteCtrl'
	}).state('post',{ 
		url:'/post',
		templateUrl:'view/template/post.html',
		controller:'postCtrl'
	});
	$urlRouterProvider.otherwise('main');	
}])